spring:
  cloud:
    stream:
      function:
        definition: publishEventToKafka;paymentEventConsumer
      bindings:
        publishEventToKafka-out-0:
          destination: order-event
        paymentEventConsumer-in-0:
          destination: payment-event